export const Url = {
    getList: "/cig/<%=type%>",
    update: "/cig/<%=type%>/<%=id%>",
    delete: "/cig/<%=type%>/<%=id%>",
    save: "/cig/<%=type%>",
    getItem: "/cig/<%=type%>/<%=id%>",

    removeFile: "/cig/removeFile",
    getDeviceByStatus: "/cig/getDeviceByStatus",
    proveApplication: "/cig/provetest/<%=id%>",
    rejectApplication: "/cig/rejecttest/<%=id%>",
    changeApplication: "/cig/changestatus/<%=id%>",
    login: "/cig/login",
    resetPassword: "/cig/resetPassword",
    resetUserPassword: "/cig/resetUserPassword",
    importInsList: "/cig/importInsList",
    importReport: "/cig/importReport",
    getMenuList: "/cig/getMenuList",
    getHeaderList: "/cig/getHeaderList",
    saveColListSet: "/cig/setHeaderList",
    getAuthList: "/cig/getAuthList",
    getInsLog: "/cig/getInsLog",
    exportInsList: "/cig/exportInsList",
    confirmInit: "/cig/confirmInit",
    updateUserInfoFromHRS: "/cig/common/importUser",
    transferAuth: "/cig/transferAuth",
    resetUserOwnPassword: "/cig/resetUserOwnPassword",
    checkUserLogin: "/cig/checkUrlLogin",
    removeAttachFile: "/cig/removeAttachFile",
    getInvalidList: "/cig/getInvalidList",
}